Forum:
    path:      /forum
    controller: FrankProjects\UltimateWarfare\Controller\Forum\ForumController::index

Forum/Category:
    path:      /forum/category/{categoryId}
    controller: FrankProjects\UltimateWarfare\Controller\Forum\CategoryController::category
    requirements:
        categoryId: '\d+'

Forum/Category/Create:
    path:      /forum/category/create/
    controller: FrankProjects\UltimateWarfare\Controller\Forum\CategoryController::create

Forum/Category/Edit:
    path:      /forum/category/edit/{categoryId}
    controller: FrankProjects\UltimateWarfare\Controller\Forum\CategoryController::edit
    requirements:
        categoryId: '\d+'

Forum/Category/Remove:
    path:      /forum/category/remove/{categoryId}
    controller: FrankProjects\UltimateWarfare\Controller\Forum\CategoryController::remove
    requirements:
        categoryId: '\d+'

Forum/Post/Edit:
    path:      /forum/post/edit/{postId}
    controller: FrankProjects\UltimateWarfare\Controller\Forum\PostController::edit
    requirements:
        postId: '\d+'

Forum/Post/Remove:
    path:      /forum/post/remove/{postId}
    controller: FrankProjects\UltimateWarfare\Controller\Forum\PostController::remove
    requirements:
        postId: '\d+'

Forum/Topic:
    path:      /forum/topic/{topicId}
    controller: FrankProjects\UltimateWarfare\Controller\Forum\TopicController::topic
    requirements:
        topicId: '\d+'

Forum/Topic/Create:
    path:      /forum/topic/create/{categoryId}
    controller: FrankProjects\UltimateWarfare\Controller\Forum\TopicController::create
    requirements:
        categoryId: '\d+'

Forum/Topic/Edit:
    path:      /forum/topic/edit/{topicId}
    controller: FrankProjects\UltimateWarfare\Controller\Forum\TopicController::edit
    requirements:
        topicId: '\d+'

Forum/Topic/Remove:
    path:      /forum/topic/remove/{topicId}
    controller: FrankProjects\UltimateWarfare\Controller\Forum\TopicController::remove
    requirements:
        topicId: '\d+'

Forum/Topic/Sticky:
    path:      /forum/topic/sticky/{topicId}
    controller: FrankProjects\UltimateWarfare\Controller\Forum\TopicController::sticky
    requirements:
        topicId: '\d+'

Forum/Topic/Unsticky:
    path:      /forum/topic/unsticky/{topicId}
    controller: FrankProjects\UltimateWarfare\Controller\Forum\TopicController::unsticky
    requirements:
        topicId: '\d+'

